version: '3.8'
services:
  application:
    container_name: main_nest_application
    image: watchzone:latest
    restart: always
    command: dev
    ports:
      - 3000:3000

    depends_on:
      - database
    networks:
      - app_network
  database:
    container_name: pg_container
    image: postgres
    volumes:
      - ./data/database:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: watchzone
    ports:
      - "5432:5432"
    networks:
      - app_network
  # supertokens:
  #   image: registry.supertokens.io/supertokens/supertokens-postgresql:6.0
  #   depends_on:
  #     - database
  #   ports:
  #     - 3567:3567
  #   environment:
  #     - POSTGRESQL_CONNECTION_URI=value
  cache:
    image: redis:6
    networks:
      - app_network

  directus:
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
    depends_on:
      - cache
      - database
    networks:
      - app_network
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'watchzone'
      DB_USER: 'root'
      DB_PASSWORD: 'root'
      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'd1r3ctu5'
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
